# Generated by Django 6.0.7 on 2026-07-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='100% Reposado Tequila (700ml)', max_length=200)),
                ('description', models.TextField(blank=True, default='Standard cradle-to-gate inventory for aged tequila.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=150)),
                ('category', models.CharField(default='General', max_length=100)),
                ('query', models.CharField(blank=True, help_text='Search query for background database matching', max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('unit', models.CharField(default='kg', max_length=30)),
                ('location', models.CharField(blank=True, default='MX', max_length=10, null=True)),
                ('exchange_type', models.CharField(choices=[('technosphere', 'Technosphere Input'), ('biosphere', 'Biosphere Emission'), ('production', 'Production Output')], default='technosphere', max_length=20)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='lca_engine.inventoryscenario')),
            ],
        ),
    ]
