# Generated by Django 6.0.7 on 2026-07-30 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lca_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Producer or Distillery Name', max_length=200)),
                ('location', models.CharField(default='Jalisco, Mexico', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryscenario',
            name='is_baseline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryscenario',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inventoryexchange',
            name='exchange_type',
            field=models.CharField(choices=[('technosphere', 'Technosphere Input'), ('biosphere', 'Biosphere Emission'), ('production', 'Production Output'), ('byproduct', 'Byproduct Credit')], default='technosphere', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryscenario',
            name='description',
            field=models.TextField(blank=True, default='Cradle-to-gate inventory process.'),
        ),
        migrations.AlterField(
            model_name='inventoryscenario',
            name='name',
            field=models.CharField(default='Standard Inventory Scenario', max_length=200),
        ),
        migrations.CreateModel(
            name='LCAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwp_total', models.FloatField(default=0.0, help_text='Total Climate Footprint in kg CO2-eq')),
                ('water_footprint_aware', models.FloatField(default=0.0, help_text='AWARE Water Scarcity Footprint in m3 world-eq')),
                ('biogenic_co2', models.FloatField(default=0.0, help_text='Direct biogenic CO2 emissions in kg')),
                ('raw_json_results', models.JSONField(default=dict, help_text='Complete calculation payload for client charts')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lca_result', to='lca_engine.inventoryscenario')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tequila_class', models.CharField(choices=[('blanco', 'Blanco / Silver (Unaged)'), ('reposado', 'Reposado (Aged 2-12 months)'), ('anejo', 'Añejo (Aged 1-3 years)'), ('extra_anejo', 'Extra Añejo (Aged 3+ years)')], default='reposado', max_length=20)),
                ('bottle_weight_g', models.FloatField(default=550.0, help_text='Weight of glass bottle in grams')),
                ('aging_months', models.IntegerField(default=6, help_text='Months spent in oak barrels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lca_engine.producer')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryscenario',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='lca_engine.product'),
        ),
    ]
