# Generated by Django 6.0.7 on 2026-08-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lca_engine', '0002_producer_inventoryscenario_is_baseline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryexchange',
            name='supplier_gwp_factor',
            field=models.FloatField(blank=True, help_text='Custom kg CO2-eq per unit from verified supplier', null=True),
        ),
        migrations.AddField(
            model_name='inventoryexchange',
            name='supplier_water_factor',
            field=models.FloatField(blank=True, help_text='Custom m3 world-eq per unit from verified supplier', null=True),
        ),
    ]
