# Generated by Django 6.0.7 on 2026-08-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lca_engine', '0003_inventoryexchange_supplier_gwp_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryscenario',
            name='captured_payload',
            field=models.JSONField(blank=True, default=dict, help_text='JSON payload mapping django_field to amounts and tier1 factors'),
        ),
        migrations.CreateModel(
            name='FallbackEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_field', models.CharField(db_index=True, max_length=100)),
                ('reporting_year', models.IntegerField(db_index=True)),
                ('emission_factor', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('indicator', models.CharField(default='GWP100', max_length=50)),
                ('source_reference', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'unique_together': {('django_field', 'reporting_year')},
            },
        ),
    ]
