# Generated by Django 6.0.7 on 2026-08-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lca_engine', '0004_inventoryscenario_captured_payload_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fallbackemissionfactor',
            unique_together={('django_field', 'reporting_year', 'indicator')},
        ),
    ]
